1. If I have a list x = [1, 2, 3] and I run the code x * 2, what is the output?

In [1]:
import numpy as py
x=py.array([1,2,3])
print(x*2)

[2 4 6]


2. Imagine you have two 3x3 matrices represented as lists of lists. How would you write the standard Python code to add them together, number by number?

In [7]:
import numpy as py
x=py.array([[1,2,3],[2,3,4],[4,5,6]])
y=py.array([[3,4,5],[1,5,6],[2,3,4]])
print(py.stack((x,y),axis=1))

[[[1 2 3]
  [3 4 5]]

 [[2 3 4]
  [1 5 6]]

 [[4 5 6]
  [2 3 4]]]
